[client]
toolbarMode = "viewer"

[server]
address="0.0.0.0"
port=8501
enableStaticServing = true

# Define your custom font families
[[theme.fontFaces]]
family = "SpaceGrotesk"
url = "app/static/fonts/SpaceGrotesk-VariableFont_wght.ttf"

[[theme.fontFaces]]
family = "SpaceGroteskHeader"
url = "app/static/fonts/SpaceGrotesk-SemiBold.ttf"

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/fonts/SpaceMono-Bold.ttf"
style = "normal"
weight = 700

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/fonts/SpaceMono-BoldItalic.ttf"
style = "italic"
weight = 700

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/fonts/SpaceMono-Italic.ttf"
style = "italic"
weight = 400

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/fonts/SpaceMono-Regular.ttf"
style = "normal"
weight = 400

[theme]
primaryColor = "#F4AA41"
backgroundColor = "#F9F9F9"
# backgroundColor = "#ffffff"
secondaryBackgroundColor = "#F9F9F9"
textColor = "#3d3a2a"
linkColor = "#3d3a2a"
borderColor = "#EDEDED"
showWidgetBorder = true
baseRadius = "0.6rem"
font = "SpaceGrotesk"
headingFont = "SpaceGroteskHeader"
codeFont = "SpaceMono"
codeBackgroundColor = "#ecebe4"
showSidebarBorder = true

[theme.sidebar]
backgroundColor = "#e8e7dd"
secondaryBackgroundColor = "#ecebe3"
